platform :ios, "5.0"
pod 'JSONKit',       '~> 1.5pre'
pod 'UAModalPanel',	'~> 1.1.1'
pod 'RestKit'
pod 'UIGlossyButton'
pod 'HockeySDK'
pod 'unoffical-twitter-sdk'
pod 'KNMultiItemSelector'
pod 'PopoverView', '~> 0.0.1'
